run:
  skip-dirs:
    - go/cmd/oracle # skip because of windows syscall

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - goconst
    - gocritic
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

output:
  sort-results: true

linters-settings:
  goimports:
    local-prefixes: github.com/kahlys/battools
  goconst:
    min-occurrences: 5
