output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - goconst
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/kahlys/battools
  goconst:
    min-occurrences: 5
